### PR TITLE
fix(roles): update role name for approval notifications in appmarketplace

### PR DESCRIPTION
**Pull request by typecastcloud**
## Description

For appmarketplace, changed approveAppUserRoles role1 to "App Manager".

## Why

Currently Service Manager receives notifications regarding app approval process. App Manager seems to be the appropriate user role to receive this notification.

## Issue

Refs:  #370

## Checklist

- [x] I have performed a self-review of my changes

### CODE REVIEW

**Comment by typecastcloud** [comment]
@evegufy please tell me if I should rebase to main.

**Comment by evegufy** [comment]
> @evegufy please tell me if I should rebase to main.

the branch is perfect, no rebase needed

**Review by evegufy — APPROVED** [review]

**Comment by evegufy** [comment]
@typecastcloud thanks for the fix!
I'm not merging directly to leave other reviewers the chance to have a look as well.

**Review by tfjanjua — APPROVED** [review]
@typecastcloud , since you have removed `Service Manager` because it was the wrong role placed under the `AppMarketplace` param, please make sure that the `Service Manager` role is placed in the correct position.

This change will resolve the issue of App Manager so, change looks fine to me though.

**Pull request merged**
